### ISSUE TITLE
Migration Issues

### ISSUE THREAD

**Issue by russssl** [jthinking/tauri-seaorm-template#2]
I was using your template and created a new migration but then I encountered a mistake and wanted to re-do the process, deleting all .ignore files and at some point re-doing the project from the beginning. but I still have this error when running project "Migration file of version 'migration_name' is missing, this migration has been applied but its file is missing. i suppose it is hidden somewhere in the system but I do not know where

**Comment by russssl** [comment]
Unfortunately, I do not have any database view, auto-generated queries, or so on to see the database myself. It seems like your template does not have ANY files connected to the database itself

**Comment by russssl** [comment]
Actually, I tried running your template and it does not work as well

**Comment by jiabochao** [comment]
You can try the following steps to see if it resolves your issue.


1. Installing sea-orm-cli

```bash
cargo install sea-orm-cli
```

2. Changing working directory

```bash
cd src-tauri
```

3. Creating new migration 

> using default directory `./migration`

```bash
sea-orm-cli migrate generate create_post_table
```

4. Updating dev database

> using `DATABASE_URL` var in `.env` file.

```bash
sea-orm-cli migrate fresh
```

5. Regenerate entity files

```bash
rm -rf entity/src/*

sea-orm-cli generate entity -o entity/src --lib --with-serde both
```
